### ISSUE TITLE
Implement a cache for feature generation

### ISSUE THREAD

**Issue by KennethEnevoldsen** [Aarhus-Psychiatry-Research/psycop-ml-utils#101]
# Feature generation:
1. Check if feature needs generating

- [x] Is number of `prediction_time_uuids` the same? If so, source data probably hasn't changed. 
- [x] Don't generate the feature.

This doesn't solve if we change feature-generation code. One way around it is to generate the feature for some subsample of the patients and compare it to the feature store.

- [x] Check that the values are the same
- [x] Is 1.000 rows enough? We want to check for patients where the values are not equal to the fallback. See if that's possible.
    - [x] Retry feature generation if all rows are equal to `fallback`

a. If so, 

- [x] Save as:`feature_col_name` + `n_prediction_time_uuids` + `timestamp`.csv
- [x] Columns: `prediction_time_uuid`, `value`

b. Otherwise, continue

# Concatenation
Load the most recent df for each feature dict.
Concatenate all the dfs.

# Decreasing file size

- [ ] Don't store rows where the value is equal to the fallback. 
- [x] Expand those values as required (`load_cache_file` function)

**Comment by martbern** [comment]
We could also compare our feature-store to our feature-source.

E.g. a two-step process:
1. Is min-date, max-date and number of unique patient IDs the same? If so, source data probably hasn't changed.

Then, for reach feature:
2. Does the feature exist in the feature store?

This doesn't solve if we change feature-generation code. One way around it is to generate the feature for some subsample of the patients and compare it to the feature store.

That said, we hope to be able to write to disk soon.
