### ISSUE TITLE
Performance: Add dichotomous flag to `add_temporal_predictor`

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-ml-utils#118]

**Comment by bokajgd** [comment]
Is this intended for creating binary/dichotomous predictors?

**Comment by MartinBernstorff** [comment]
Yep! If it's set and implemented, it allows vectorisation of a bunch of the computations. See the implementation in `add_temporal_outcome` for an example.

**Comment by bokajgd** [comment]
Amazing, I will delete my issue regarding adding this feature using a resolve_multiple function.
