### ISSUE TITLE
Feature report for error checking

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/psycop-ml-utils#126]
Automatically assess the data integrity of the generated features using e.g. deepchecks

**Comment by MartinBernstorff** [comment]
- [ ] Use GreatExpectations as a profiler, and then build on that?
- [ ] Have GreatExpectations as a profiler on loader ingest, then create a feature report afterwards?

**Comment by HLasse** [comment]
[Deepcheck's data integrity](https://docs.deepchecks.com/stable/user-guide/tabular/auto_quickstarts/plot_quick_data_integrity.html) looks ideal, but has wack dependencies to we can't install it with poetry..
