### ISSUE TITLE
Validate raw data

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/psycop-ml-utils#127]
Check for consistency in dtypes in columns etc (some of the automated tools mentioned in https://github.com/Aarhus-Psychiatry-Research/psycop-t2d/issues/150 do the trick) if not already done? 

- [ ] Check all loaders once with e.g. deepchecks before committing? 

Somewhat aligns with #78

**Comment by MartinBernstorff** [comment]
These notes are excellent, Lasse!

Looking at evidently and whylogs, their model performance suites seem very minimal. I think we can build their functionality *very* quickly ourselves, and then not be bound by their frameworks.
