### ISSUE TITLE
Fix links to documentation in readme

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/psycop-ml-utils#130]
All documentation links are currently broken. (not super high priority)

**Comment by KennethEnevoldsen** [comment]
I can't find any which are broken. Can you give an example?

**Comment by HLasse** [comment]
Hm, Usage Guides and News and Changelogs but obviously they don't exist yet. Sorry about that, will close the issue

**Comment by KennethEnevoldsen** [comment]
I will remove them. I have created a PR on it.
