### ISSUE TITLE
resolve multiple function for binary features

### ISSUE THREAD

**Issue by bokajgd** [Aarhus-Psychiatry-Research/psycop-ml-utils#144]
Create a resolve multiple function that handles a numeric value column but returns a binary feature (e.g. value column is 'varighed af tvangshændelse' and desired feature is a binary 'tvang_occured_within_x_months')

**Comment by bokajgd** [comment]
Not a pretty solution but it was the best I could think of. Any nice ideas before submitting PR @MartinBernstorff? Does the purpose of the function make sense?

**Comment by MartinBernstorff** [comment]
Yep, agree with everything here! Commit looks good as well – if PR passes tests, feel free to override and merge yourself 👍

**Comment by MartinBernstorff** [comment]
(Also, in the future, feel free to create a PR with the above considerations. Means I can add a review and merge immediately 😊)

**Comment by bokajgd** [comment]
Cool, everything noted. :)
