### ISSUE TITLE
Split READMEs – maybe in the package dirs? What is recommended?

### ISSUE THREAD

**Issue by martbern** [Aarhus-Psychiatry-Research/psycop-ml-utils#15]

**Comment by HLasse** [comment]
I'd recommend using [Sphinx](https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html) for documentation. Easily scalable, looks good, and a nice way to get an overview of all functionality. Also used for [DaCy](https://centre-for-humanities-computing.github.io/DaCy/) and [TextDescriptives](https://hlasse.github.io/TextDescriptives/)

**Comment by HLasse** [comment]
@KennethEnevoldsen got that boilerplate code?

**Comment by KennethEnevoldsen** [comment]
Added to my todo after the 20th :)
