### ISSUE TITLE
Why are there still duplicates?

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-ml-utils#165]
Feature sets generate a ~2k duplicates of the same patient?!

We don't know why this specific patient causes it:
- [x] Removing duplicates from load_physical_visits

- [x] Fix errors in diagnosis loaders

- [x] Generate new dataset

- [x] Check for number of duplicates now

Still 0.3% duplicates. Considering:
- [x] In `timeseriesflattener`, check whether there are duplicates after initialisation.

- [x] In `timeseriesflattener`, if n_workers = 1, don't parallelise. Allows to step through and run a `check_for_duplicates` function at opportune times.

- [x] Create a `load_all_from_id` function that finds all information collected on a given patient, given a `predictor_dict_list`

**Errors found (cumulative)**:

- [x] 1472 duplicates introduced via `add_temporal_outcome`

- [x] 2942 in `add_static_info`

- [x] 5324 after `add_temporal_predictors`

- [x] Generate new dataset and check for duplicates
 - [x] 0.07% duplicates. Wtf? When is this happening? Train ids have 4 duplicates. Check that out.
 - [x] Get new train, test and val ids from Freud to Overtaci
 - [x] Install psycopmlutils
 - [x] Upload to SQL
 - [x] Check for duplicates in IDs
 - [x] Commit changes to psycop-tts
 - [x] New dataset (in progress)
 - [x] Commit changes to `psycop-ml-utils`

**Comment by MartinBernstorff** [comment]
- [ ] How do we error-check this in the future? Make a list of all input dfs and run checks on them?
    - [ ] Set pandas `validate` flag

- [ ] Check raw data for 
    - [ ] Full duplicates
    - [ ] Timestamp + dw_ek_borger duplicates
    - [ ] NaT prop
    - [ ] NaN prop

**Comment by HLasse** [comment]
@MartinBernstorff can you edit with a brief summary of what happened (for posterity)?
