### ISSUE TITLE
Make `timeseriesflattener` handle text

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/psycop-ml-utils#188]
## **Edit: MVP**

1. Create a loader function that loads one/all of the specified note types (we have 17 different. Might want to just use e.g. aktuel psykisk as that was the most predictive for Andreas) and featurizes it using e.g. sentencetransformers or tf-idf.
2. Feeds this to TSFlattener and let it do its thing

The loader will return multiple columns. This should be handled by writing a new `resolve_multiple_fn`.

***

Different ways to go about this:

**Suggestion 1**
- Add a new aggregate function: `text`, which concatenates the inputs in the time range
- Handle tf-idf'ing/doc embedding/.. in the training split (in the Pipeline).

Pros: 
- Maximal flexibility to do whatever with the text in the training pipeline
- Saves TF-IDF/count vectorizer.. in the training pipeline to use for evaluation/cross-validation

Cons:
- Very memory intensive. Each note will be replicated multiple times if multiple lookbehind windows
- Slow training as we would need to featurize as well

**Suggestion 2**
- Aggregate featurized inputs in the time range directly in TSFlattener

Pros:
- Saves a bunch of memory
- Does not require us to do any featurization in the training script
- Faster training

Cons:
- Can't do CV without some leakage (if using e.g. TF-IDF)

After writing it out I'm personally leaning towards option 2. Any thoughts, @MartinBernstorff , @KennethEnevoldsen?

**Comment by KennethEnevoldsen** [comment]
Can we save the text? Concatenation does not seem like an optimal strategy for text.

I would imagine that an average text embedding and a latest entry text embedding. Potentially do this for each type of text entry as well as an average across all. When we create, this embedding is second order to be (whatever is easiest to implement)

**Comment by MartinBernstorff** [comment]
I can't parse @KennethEnevoldsen's second paragraph, so this might be redundant.

For scope, I imagine we focus on text-"embeddings" which can be fed to classical-ML models (XGBoost etc.). For deep learning models, I strongly expect we won't use `tsflattener`?

Given that, I feel like there are (at least) three different problems here:
1. Which text to extract
2. How to extract and save it
3. How to embed it

I imagine these interact – e.g. if low amounts of text, we can do something super simple in (2.) like aggregating for each prediction time.

Personally, I'd lean towards doing something super simple for this, and then relatively quickly move towards a DL/sequential model :-)

**Comment by HLasse** [comment]
We actually can't save the raw text - it has to hashed in some form (tf-idf, count vectorized, wordpieces mapped to idx are all legit options). 

Sure, calculating embeddings on a by-note basis and averaging/aggregating is a good idea. Updated option 2 to reflect that. 

We should probably train a count/tf-idf vectorizer on the training data which we then call in TSFlattener to do the featurization in that case.

**Comment by HLasse** [comment]
I see a fairly simple MVP:

1. Create a loader function that loads one/all of the specified note types (we have 17 different. Might want to just use e.g. `aktuel psykisk` as that was the most predictive for Andreas) and featurizes it using e.g. sentencetransformers or tf-idf. 
2. Feeds this to TSFlattener and let is do its thing

**Comment by MartinBernstorff** [comment]
> I see a fairly simple MVP:
> 
> 1. Create a loader function that loads one/all of the specified note types (we have 17 different. Might want to just use e.g. `aktuel psykisk` as that was the most predictive for Andreas) and featurizes it using e.g. sentencetransformers or tf-idf.

Agreed!

> 2. Feeds this to TSFlattener and let it do its thing
> 
> @MartinBernstorff can TSFlattener handle multiples values in the feature df?

Sure! We might trip some of my validation functions, but should be easy to fix.

**Comment by HLasse** [comment]
Cool, will get on it ASAP

**Comment by MartinBernstorff** [comment]
Sure thing! I'll try and get some model training going!

**Comment by MartinBernstorff** [comment]
I expect this'll be _super_ slow though. We might want to get some column caching up and running for faster iteration.

**Comment by HLasse** [comment]
Yeah, that sounds like a fairly high priority! Bump #101 in the queue?

**Comment by MartinBernstorff** [comment]
> > I see a fairly simple MVP:
> > 
> > 1. Create a loader function that loads one/all of the specified note types (we have 17 different. Might want to just use e.g. `aktuel psykisk` as that was the most predictive for Andreas) and featurizes it using e.g. sentencetransformers or tf-idf.
> 
> Agreed!
> 
> > 2. Feeds this to TSFlattener and let it do its thing
> > 
> > @MartinBernstorff can TSFlattener handle multiples values in the feature df?
> 
> Sure! We might trip some of my validation functions, but should be easy to fix.

And amendment to this. As far as I can tell, all we need is to ensure that we have a `resolve_multiple` function which can aggregate in the way we want to.

**Comment by KennethEnevoldsen** [comment]
An alternative is to create a bash script to run dataset creation and training with user input. Should be easy to setup and maintain (an alternative is using make or snakemake)

**Comment by MartinBernstorff** [comment]
> An alternative is to create a bash script to run dataset creation and training with user input. Should be easy to setup and maintain (an alternative is using make or snakemake)

Alternative to?
