### ISSUE TITLE
Re-add darglint?

### ISSUE THREAD

**Issue by KennethEnevoldsen** [Aarhus-Psychiatry-Research/psycop-ml-utils#204]
(creating an issue as @MartinBernstorff removed it in #186)

The original idea was to not have people correct incorrect types but have darglint. Darglint is still notably faster than a code review (and it is frustrating to check types). I see that it shouldn't be a pre-commit hook.

**Comment by MartinBernstorff** [comment]
I really love the functionality as well! 

But I think the friction is too costly.

We can avoid some of the pain from code-reviews by:
1. If the only errors are types in docstrings, approve the review but ask for them to be fixed. Saves a review cycle.
2. Not be too stringent re: types in docstrings. They should be corrected, yes, but worst-case is some lacking documentation.

I think the github workflow might be too slow a feedback loop – I worry the increased friction is more harmful to motivation/morale than the gain from linting the docstrings.

I'll prefer keeping CI as light weight as possible. @HLasse, @frillecode, @bokajgd, @erikperfalk, what is your stance on this?

**Comment by KennethEnevoldsen** [comment]
(1 doesn't work with auto-merge, 2 worse case is user error due to docstring leading to uncaught error)

Darglint is on:

Worst case: I create a PR with a feature and request a review. Darglint complains that "Str, optional"  should be "Str". The code review passes. I (needlessly fix the darglint error). It is almost completely unlikely that darglint will take longer than the code review. --> Conclusion coder timer is wasted (1-5min)

Darglint is off (people validate type hints):

Worst case: I create a PR with a feature and request a review. Others find multiple errors in type hints (potentially not all, see next case) and spend time correcting them, potentially missing more important errors in the code. After these are fixed, the code looks good to them. --> Conclusion reviewer time is wasted (1-10min), and potentially more bugs are uncaught (assumption).

Darglint is off (people don't validate type hints):

Worst case: I create a PR with a feature and request a review. Others find errors in type hints but don't fix them because they want to focus on meaningful changes. Later on, a user misunderstands the documentation, spending time debugging the code. --> Conclusion user time is wasted (10min-2h) or worse, a person inputs a wrong type leading to an uncaught error.

Darglint is on:

Average case: I create a PR with a feature and request a review. Others find multiple errors in type hints (but disregard them because they know darglint will handle them) and makes code corrections. I fix the correction along with the darglint corrections. --> Conclusion reviewer time is saved (1-5min), coder time is stable.


For me, I see a relatively small downside compared to the upside (assuming that we have already agreed to review each others' code).
I agree that the friction with using it as a pre-commit is annoying.

**Comment by KennethEnevoldsen** [comment]
I see. I typically just run through the list once (I would say 1/10 I do it twice). 

I still think it is worth it though, but I am not the one writing most of the code on this repo so maybe it shouldn't be me who makes the call. So will close this for now then someone else can open it if they feel otherwise.

**Comment by MartinBernstorff** [comment]
Nah, I totally think we should have people chime in! You review a large chunk of the code (which I'm **super** grateful for), so your voice is super important!
