### ISSUE TITLE
Conda downloader pakker på C:

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/psycop-ml-utils#257]
Hej Mathias og Line,

Vi er skiftet til at lave vores conda-miljøer på E-drevet da C er fuldt. Conda insisterer dog stadig på at gemme en kopi afpakkerne på C drevet (under `user/.conda/pkgs`) hvilket giver problemer hvis der ikke plads. 

Det virker til at man kan løse det ved at ændre i den globale `.condarc` fil og sætte `pkgs_dirs`til et sted på E i stedet som i [denne post](https://stackoverflow.com/questions/57697342/set-a-path-for-the-conda-pkgs-directory). 

Kan en af jer hjælpe med det? :)

**Comment by mbroend** [comment]
Tjek, burde være løst nu. Sat stien til E:\ProgramData\Anaconda3\share\conda
