### ISSUE TITLE
`resolve_multiple` `sum`, `count`

### ISSUE THREAD

**Issue by martbern** [Aarhus-Psychiatry-Research/psycop-ml-utils#32]
Might be helpful for e.g. "numbers of times admitted with diagnosis code within n months".

**Comment by bokajgd** [comment]
Similarly I could also use something along the lines of "get_n_events_from_list_of_events" for e.g. "number of tvangshændelser within last n months". Maybe as simple as:

def get_n_events_from_list_of_events(list_of_events: List[Tuple[Union[datetime, float]]]) -> int:
    """
    Documentation
    """
    return len(list_of_events)

**Comment by martbern** [comment]
True! Quite strong overlap with `sum`, though, just code each visit with a value of "1".

**Comment by bokajgd** [comment]
Yes, that's true - might be nice to have a separate function now that the implementation is so easy. Looks good. Thanks for showing the code-highlighting function.
