### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by martbern** [Aarhus-Psychiatry-Research/psycop-ml-utils#44]
Currently ~180s per feature.

- [ ] Do `add_col_to_flattened_dataset` with dfs to allow for vectorisation?
- [x] Replace pandas `.apply` with dask?
- [ ] #48

**Comment by martbern** [comment]
Tried using dask:
* [PR](https://github.com/Aarhus-Psychiatry-Research/psycop-ml-utils/pull/45)
* [Application](https://github.com/Aarhus-Psychiatry-Research/t2d/blob/main/src/feature_generation/create_prediction_dataframe.py)

Doesn't seem to work on the Windows server. Only 3% CPU load.

Contemplating moving from a `dict` and `list` implementation to pure `pandas` for vectorisation. I expect that'll be much faster, but is probably a couple of days for a re-write.

@KennethEnevoldsen, thoughts? I'm up for a call as well 👍 

(Thanks a **ton** for the help here. Getting some good-quality shared code out seems high yield).

**Comment by KennethEnevoldsen** [comment]
Might be worth looking into [np.vectorize](https://stackoverflow.com/questions/52673285/performance-of-pandas-apply-vs-np-vectorize-to-create-new-column-from-existing-c). In general I think a vectorized solution is generally more stable.

**Comment by martbern** [comment]
I tried looking into a map, but the issue is that we need a value from each row and pass it as an argument to the function we're mapping onto the row. E.g. we need the prediction_time's date to know whether an outcome is within n days from it.

As I understand it, this means we need an apply?

**Comment by martbern** [comment]
Getting started on using `pandas.DataFrame` for vectorisation.
