### ISSUE TITLE
Temporal representation

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-ml-utils#52]
E.g. generate both "last value" and "time since last value". Would allow the model to learn interaction terms between these two.

**Comment by martbern** [comment]
Have implemented something similar with `keep_val_timestamp` in `add_temporal_col_to_flattened_dataset`. All that's probably needed is a `keep_predictor_timestamp` flag for `add_temporal_predictor` as well as a handling of:
- [ ] What if resolve_multiple doesn't make sense for the timestamps? E.g. what is the timestamp of "mean"?
- [ ] What timestamp do we assign if using fallback?
