### ISSUE TITLE
`resolve_multiple` slope

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-ml-utils#53]
As a strategy for `resolve_multiple`, calculate the slope. #52.

**Comment by martbern** [comment]
Additions:
- [ ] Add `variance_as_fraction_of_mean` to `assert_outcome` and `assert_predictor`
- [ ] Update docstrings
- [ ] Add tests for `variance_as_fraction_of_mean` and `is_fallback_prop_warning_threshold`

**Comment by bokajgd** [comment]
Addition to addition:

- [ ] Assert for warning message for low variance threshold mm.
