### ISSUE TITLE
`incident` boolean parameter for `add_outcome`

### ISSUE THREAD

**Issue by martbern** [Aarhus-Psychiatry-Research/psycop-ml-utils#71]
If we are only interested in incident outcomes, remove all prediction times after the eventt. (E.g. diagnosing diabetes after it has already been diagnosed isn't helpful).

**Comment by martbern** [comment]
@KennethEnevoldsen Just spoke to @HLasse about this. We'll definitely need the functionality at evaluation time. 

However, unsure about whether to keep prediction times after diagnosis when training. On one hand, it's kind of a separate category **"has diabetes"** vs. "high risk of getting diabetes" vs. "low risk of getting diabetes". On the other hand, **"has diabetes"** vs. "high risk of getting diabetes" are probably much closer to each other than to "low risk of getting diabetes", so lumping them together during training could be beneficial. 

Maybe something we should explore empirically. 

I've created a new mode training repo and added an issue [here](https://github.com/Aarhus-Psychiatry-Research/model-training/issues/1).

**Comment by KennethEnevoldsen** [comment]
Hmm, I would say probably don't keep it would seem the most valid, but I see why it might help the model learn. Def. the test set should include this.

It seems like an obv. thing to check though. We should add it to the grid search
